name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: 1.5.1
        path: pico-sdk-1.5.1
        submodules: recursive

    - name: Install tools
      run: sudo apt-get install -y build-essential cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=waveshare_rp2040_one -DPICO_SDK_PATH=${{github.workspace}}/pico-sdk-1.5.1/

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UF2
        path: ${{github.workspace}}/build/con.uf2
